---
- debug:
    msg: common role

- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  become: yes

- name: Install essential packages
  apt:
    name: 
      - tree
      - tmux
      - vim
      - git
    update_cache: yes
  become: yes

- name: create user
  user:
    name: jan
    shell: /bin/bash
    password: "jan"
  become: yes

- set_fact:
    bruce: lee

