---

- name: install packages
  package:
    name: "{{ item }}" 
  with_items:
    - vim

- name: copy files 
  copy:
    src: "../../../files/vim/"
    dest: "{{ user.home }}/.vim"
    owner: "{{ user.name }}"

- name: create symlinks
  file:
    src: "{{ user.home }}/.vim/{{ item }}"
    dest: "{{ user.home }}/.{{ item }}"
    state: link
  with_items:
    - vimrc
    - gvimrc

- name: clone plugins
  git:
    repo: "{{ item.url }}"
    dest: "{{ user.home }}/.vim/bundle/{{ item.name }}"
    ssh_opts: -o StrictHostKeyChecking=no
    accept_hostkey: yes
  with_items:
    - { name: 'nerdtree', url: 'https://github.com/scrooloose/nerdtree' }
    - { name: 'ansible-vim', url: 'https://github.com/scrooloose/nerdtree' }

