#!/bin/bash

prompt_command() {
  local last_exit_code="$?"
  history -a
  find_git_branch
  find_git_dirty
  find_exit_code $last_exit_code
  find_awsume_role
}

find_awsume_role() {
  if [[ "$AWSUME_PROFILE" ]]; then
    aws_role="($AWSUME_PROFILE)"
  fi
}

find_git_branch() {
  local branch
  if branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null); then
    if [[ "$branch" == "HEAD" ]]; then
      branch='detached*'
    fi
    git_branch="($branch)"
  else
    git_branch=''
  fi
}

find_git_dirty() {
  local status=$(git status --porcelain 2> /dev/null)
  if [[ "$status" != "" ]]; then
    git_dirty='*'
  else
    git_dirty=''
  fi
}

find_exit_code() {
  if [[ $1 == 0 ]]; then
    exit_code=''
  else
    exit_code=':( '
  fi
}

function p
{
    cd $PROJECTS_HOME/$1
}

_p()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=`ls -la $PROJECTS_HOME | grep -e '^d' | awk '{print $9}' | grep -v '^\.'`
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

function n
{
    vim $NOTES_HOME/$1
}

function n-show
{
    cat $NOTES_HOME/$1
}

_n()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=`find $NOTES_HOME -maxdepth 1 -name "*.txt" -type f -printf "%f\n"`
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}
complete -F _p p
complete -F _n n
complete -F _n n-show
