#!/bin/bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias t='tree -A -L 2'
alias vi='vim'
alias tailf='tail -f'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias pstree='pstree -ahp'
alias venv2='virtualenv --python=python2 venv2'
alias venv3='virtualenv --python=python3 venv3'

if [[ $THIS_OS == 'macos' ]]; then
  alias ls='ls -laG'
else
  alias ls='ls -la --color=auto'
fi

if [[ `which awsume` ]]; then
  #AWSume alias to source the AWSume script
  alias awsume=". awsume"

  #Auto-Complete function for AWSume

  _awsume() {
      local cur prev opts
      COMPREPLY=()
      cur="${COMP_WORDS[COMP_CWORD]}"
      prev="${COMP_WORDS[COMP_CWORD-1]}"
      opts=$(awsumepy --rolesusers)
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
  }
  complete -F _awsume awsume
fi
