#!/bin/bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias t='tree -A -L 2'
alias vi='vim'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias pstree='pstree -ahp'

if [[ $THIS_OS == 'macos' ]]; then
  alias ls='ls -laG'
else
  alias ls='ls -la --color=auto'
fi
