# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# set vi mode
set -o vi

export THIS_OS='linux'
if [[ $OSTYPE == 'darwin18' ]]; then
  export THIS_OS='macos'
fi

if [ -f $HOME/.bash_colors ]; then
    source $HOME/.bash_colors
fi
if [ -f $HOME/.bash_functions ]; then
    source $HOME/.bash_functions
fi
if [ -f $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases
fi
if [ -f $HOME/.gitcompletion ]; then
    source $HOME/.gitcompletion
fi
if [ -f $HOME/.gitprompt ]; then
    source $HOME/.gitprompt
fi

# history
#
# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth:erasedups
# append to the history file, don't overwrite it
shopt -s histappend
HISTTIMEFORMAT='%F %T '
HISTSIZE=99999
HISTFILESIZE=99999

# prompt
#
# Show if there are unstaged (*) and/or staged (+) changes
export GIT_PS1_SHOWDIRTYSTATE=1
# Show if there are untracked files (%)
export GIT_PS1_SHOWUNTRACKEDFILES=1
# Show how we're tracking relative to upstream
export GIT_PS1_SHOWUPSTREAM="auto verbose name"
# Show colours in bash prompt
export GIT_PS1_SHOWCOLORHINTS=""
# Show if there is anything stashed ($)
export GIT_PS1_SHOWSTASHSTATE=1

# trigger function that export variables used in prompt
PROMPT_COMMAND=prompt_command

# PS1=this is set in bash_functions

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
export LESS_TERMCAP_md=$(tput bold; tput setaf 6) # cyan
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # yellow on blue
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) # white
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

export EDITOR="vim"
export PROJECTS_HOME="$HOME/Projects"
export ENVIRONMENTS_HOME="$HOME/data/dev/environments"

export JAVA_HOME="$HOME/data/dev/environments/java/jdk/java"
if [[ $THIS_OS == 'macos' ]]; then
  export JAVA_HOME="$(/usr/libexec/java_home -v 12)"
fi
export MAVEN_HOME="$HOME/data/dev/environments/java/maven3"
if [[ $THIS_OS == 'macos' ]]; then
  export MAVEN_HOME="/usr/local/Cellar/maven/3.5.3"
fi

USER_BIN="${HOME}/bin"
USER_LOCAL_BIN="${HOME}/.local/bin"

if [ -d "${RBENV_ROOT}" ]; then
  export PATH="${RBENV_ROOT}/bin:${PATH}"
  eval "$(rbenv init -)"
fi
if [ -d "${USER_BIN}" ]; then
  export PATH="${USER_BIN}:${PATH}"
fi
if [ -d "${USER_LOCAL_BIN}" ]; then
  export PATH="${USER_LOCAL_BIN}:${PATH}"
fi
if [ -d "${JAVA_HOME}" ]; then
  export PATH="${JAVA_HOME}/bin:${PATH}"
fi
if [ -d "${MAVEN_HOME}" ]; then
  export PATH="${MAVEN_HOME}/bin:${PATH}"
fi
