# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export THIS_OS='linux'
if [[ $OSTYPE == 'darwin17' ]]; then
  export THIS_OS='macos'
fi

if [ -f $HOME/.bash_colors ]; then
    source $HOME/.bash_colors
fi
if [ -f $HOME/.bash_functions ]; then
    source $HOME/.bash_functions
fi
if [ -f $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases
fi
if [ -f $HOME/.gitcompletion ]; then
    source $HOME/.gitcompletion
fi

# history
#
# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
HISTTIMEFORMAT='%F %T '
HISTSIZE=99999
HISTFILESIZE=99999

PROMPT_COMMAND=prompt_command
PS1="\[$txtred\]\$exit_code\[$txtcyn\]\u@\h\[$txtrst\] \w \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
export LESS_TERMCAP_md=$(tput bold; tput setaf 6) # cyan
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # yellow on blue
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) # white
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

export EDITOR="vim"
export PROJECTS_HOME="$HOME/data/dev/projects"
export ENVIRONMENTS_HOME="$HOME/data/dev/environments"
export NOTES_HOME="$HOME/data/dev/projects/notes"

export JAVA_HOME="$HOME/data/dev/environments/java/jdk/java"
if [[ $THIS_OS == 'macos' ]]; then
  export JAVA_HOME="$(/usr/libexec/java_home)"
fi

export MAVEN_HOME="$HOME/data/dev/environments/java/maven3"
export RBENV_ROOT="$ENVIRONMENTS_HOME/rbenv"

USER_BIN="${USER_HOME}/bin"

if [ -d "${RBENV_ROOT}" ]; then
  export PATH="${RBENV_ROOT}/bin:${PATH}"
  eval "$(rbenv init -)"
fi
if [ -d "${USER_BIN}" ]; then
  export PATH="${USER_BIN}:${PATH}"
fi
if [ -d "${JAVA_HOME}" ]; then
  export PATH="${JAVA_HOME}/bin:${PATH}"
fi
if [ -d "${MAVEN_HOME}" ]; then
  export PATH="${MAVEN_HOME}/bin:${PATH}"
fi
if [ -d "/usr/local/go" ]; then
  export GOPATH="$PROJECTS_HOME/go"
  export PATH="${PATH}:/usr/local/go/bin:${GOPATH}/bin"
fi

