#!/bin/bash

prompt_command()
{
  local last_exit_code="$?"
  history -a
  find_exit_code $last_exit_code
  find_awsume_role
  find_virtual_env
  find_proxy
  __git_ps1 "\[$txtred\]\${exit_code}\[$txtcyn\]\${virtual_env}\${proxy}\u@\h\[$txtrst\] \w" "\[$txtblu\]\${aws_role}\[$txtrst\]\$ "
}

find_virtual_env()
{
  if [[ "$VIRTUAL_ENV" ]]; then
    virtual_env="(`basename \"$VIRTUAL_ENV\"`) "
  else
    virtual_env=''
  fi
}

find_awsume_role()
{
  if [[ "$AWSUME_PROFILE" ]]; then
    aws_role="($AWSUME_PROFILE)"
  fi
}

find_exit_code()
{
  if [[ $1 == 0 ]]; then
    exit_code=''
  else
    exit_code=':( '
  fi
}

find_proxy()
{
  if [[ `env | grep 'http.\{0,1\}_proxy'` ]]; then
    proxy='-p- '
  else
    proxy=''
  fi
}

function set-env()
{
  local path=$HOME/$1
  if [ -f $path ]; then
    cat $path
    source $path
  else
    echo "Cannot find $path"
  fi
}

function p()
{
    cd $PROJECTS_HOME/$1
}

_p()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=`ls -la $PROJECTS_HOME | grep -e '^d' | awk '{print $9}' | grep -v '^\.'`
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _p p
