#!/bin/sh

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias t='tree -A -L 2'
alias vi='vim'
alias tailf='tail -f'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias pstree='pstree -ahp'

if [[ "${PLATFORM}" == "linux" ]]; then
  alias ls='ls -la --color=auto'
elif [[ "${PLATFORM}" == "darwin" ]]; then
  alias ls='ls -laG'
fi
