zmodload zsh/zprof

plugins=(zsh-autosuggestions zsh-syntax-highlighting docker docker-compose)

export TERM="xterm-256color"
export ZSH_HOME=$HOME/.zsh
export ZSH=$HOME/.oh-my-zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_THEME="powerlevel10k/powerlevel10k"
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# user configuration
platform='unknown'
unamestr=`uname`
if [ "$unamestr" = 'Linux' ]; then
   platform='linux'
elif [ "$unamestr" = 'Darwin' ]; then
   platform='darwin'
fi
export PLATFORM=$platform
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export EDITOR='vim'
export ARCHFLAGS="-arch x86_64"
export PATH="${HOME}/.local/bin:$PATH"
if [[ "${PLATFORM}" == "linux" ]]; then
  export PROJECTS_HOME="/data/dev/Projects"
elif [[ "${PLATFORM}" == "darwin" ]]; then
  export PROJECTS_HOME="${HOME}/data/dev/Projects"
fi

# vi mode
bindkey -v
export KEYTIMEOUT=5

# keybindings
bindkey -v '^?' backward-delete-char
bindkey '^R' history-incremental-search-backward

# history file
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP

# zsh-autosuggest
ZSH_AUTOSUGGEST_USE_ASYNC="true"
bindkey '^ ' forward-word # Ctrl+space

# aliases
if [ -f $ZSH_HOME/.shell_aliases ]; then
    source $ZSH_HOME/.shell_aliases
fi

# colors
if [ -f $ZSH_HOME/.shell_colors ]; then
    source $ZSH_HOME/.shell_colors
fi

# functions
if [ -f $ZSH_HOME/.shell_functions ]; then
    source $ZSH_HOME/.shell_functions
fi

# fzf
if [ -f ~/.fzf.zsh ]; then
	source ~/.fzf.zsh
	export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
	export FZF_CTRL_T_COMMAND="fd -t d . $PROJECTS_HOME"
fi

# git completion
if [ -f "$ZSH_HOME/git-completion.bash" ] &&
   [ -f "$ZSH_HOME/_git" ]; then
  zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
  fpath=(~/.zsh $fpath)
fi

# pyenv
if [ -d "$HOME/.pyenv" ] ; then
   export PYENV_ROOT="$HOME/.pyenv"
   export PATH="$PYENV_ROOT/bin:$PATH"
   eval "$(pyenv init --path)"
fi

# golang
if $(which "go" &>/dev/null); then
  export GOPATH="$HOME/go"
  export PATH="$GOPATH/bin:$PATH"
fi

# jenv
if $(which "jenv" &>/dev/null); then
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
  export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`"
  alias jenv_set_java_home='export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`"'
fi

# add completions, only update cache once a day
autoload bashcompinit && bashcompinit
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
  [ -f "/usr/local/bin/aws_completer" ] && complete -C '/usr/local/bin/aws_completer' aws
done

# This is to not invoke 'less' on various commands like aws and git
unset LESS;

