execute pathogen#infect()

filetype plugin indent on    " required

set t_Co=256
set background=dark
colorscheme distinguished

set expandtab
set shiftwidth=2
set tabstop=2
set autoindent
set cindent
set ignorecase
set smartcase
set nowrap
set paste
filetype plugin indent on

" Number of lines to use for the command line
set cmdheight=1 

" Shows a line indicating mode (ie, the -- INSERT -- at the bottom )
set showmode

" Show file position
set ruler

" Show incomplete commands in status bar. 
set showcmd

" Show cursor line by default - makes it easier to pair
set cursorline

" Always show a status line
set laststatus=2

" Configure the status line
set statusline=%F%m%a%r%=\ %y\ \ \-\ %3.3v,%5.5l/%5.5L\ %%%3.3p

" line numbers on
set number

" next/previous search results always centered
nmap n nzz
nmap s-n s-nzz
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

" incremental search
set incsearch
set hlsearch

let mapleader="\\"
map <Leader>h :set hls!<CR>
map <Leader>i :set ignorecase!<CR>
map <Leader>l :set number!<CR>
map <Leader>p :set paste!<CR>
map <Leader>c :set cursorline!<CR>

" one space after a period not two
set nojoinspaces

" Store swap files in fixed location, not current directory.
set dir=~/.vim/.vimswap//

set lazyredraw

" we hate literal tabs tabs
highlight LiteralTabs ctermbg=darkgreen guibg=darkgreen
match LiteralTabs /\s\ /

" highlight extra spaces ftw
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * redraw!
map __ :set hls!<CR>
map _ic :set ignorecase!<CR>

let mapleader="\\"
map <Leader>h :set hls!<CR>
map <Leader>n :set number!<CR>
map <Leader>p :set paste!<CR>

"vim-go
" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#cmd#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction

autocmd FileType go noremap <leader>b :<C-u>call <SID>build_go_files()<CR>
autocmd FileType go noremap <leader>T :GoTestFunc<enter>
autocmd FileType go noremap <leader>t :GoTest<enter>
autocmd FileType go noremap <leader>d :GoDef<enter>
autocmd FileType go noremap <leader>i :GoInfo<enter>
autocmd FileType go noremap <leader>c :GoCoverageToggle<enter>

map <C-n> :NERDTreeToggle<CR>
map <C-h> <C-w><C-h>
map <C-j> <C-w><C-j>
map <C-k> <C-w><C-k>
map <C-l> <C-w><C-l>

" open help in vertical split
autocmd FileType help wincmd L

syntax on
